apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xcwh8f0fu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xcwh8f0fu-go 
  name: xcwh8f0fu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xcwh8f0fu-go 
